// @ts-nocheck -- skip type checking
import * as meta_0 from "../src/content/docs/meta.json?collection=meta&hash=1747512530457"
import * as docs_11 from "../src/content/docs/components/terminal-index.mdx?collection=docs&hash=1747512530457"
import * as docs_10 from "../src/content/docs/components/serach-bar-index.mdx?collection=docs&hash=1747512530457"
import * as docs_9 from "../src/content/docs/components/retro-terminal.mdx?collection=docs&hash=1747512530457"
import * as docs_8 from "../src/content/docs/components/matrix-terminal.mdx?collection=docs&hash=1747512530457"
import * as docs_7 from "../src/content/docs/components/interactive-terminal.mdx?collection=docs&hash=1747512530457"
import * as docs_6 from "../src/content/docs/components/filter-search-bar.mdx?collection=docs&hash=1747512530457"
import * as docs_5 from "../src/content/docs/components/dropdown-search-bar.mdx?collection=docs&hash=1747512530457"
import * as docs_4 from "../src/content/docs/components/colorful-search-bar.mdx?collection=docs&hash=1747512530457"
import * as docs_3 from "../src/content/docs/components/code-terminal.mdx?collection=docs&hash=1747512530457"
import * as docs_2 from "../src/content/docs/components/base-terminal.mdx?collection=docs&hash=1747512530457"
import * as docs_1 from "../src/content/docs/components/action-search-bar.mdx?collection=docs&hash=1747512530457"
import * as docs_0 from "../src/content/docs/index.mdx?collection=docs&hash=1747512530457"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.doc<typeof _source.docs>([{ info: {"path":"index.mdx","absolutePath":"/home/shivam/Desktop/code-clamp/src/content/docs/index.mdx"}, data: docs_0 }, { info: {"path":"components/action-search-bar.mdx","absolutePath":"/home/shivam/Desktop/code-clamp/src/content/docs/components/action-search-bar.mdx"}, data: docs_1 }, { info: {"path":"components/base-terminal.mdx","absolutePath":"/home/shivam/Desktop/code-clamp/src/content/docs/components/base-terminal.mdx"}, data: docs_2 }, { info: {"path":"components/code-terminal.mdx","absolutePath":"/home/shivam/Desktop/code-clamp/src/content/docs/components/code-terminal.mdx"}, data: docs_3 }, { info: {"path":"components/colorful-search-bar.mdx","absolutePath":"/home/shivam/Desktop/code-clamp/src/content/docs/components/colorful-search-bar.mdx"}, data: docs_4 }, { info: {"path":"components/dropdown-search-bar.mdx","absolutePath":"/home/shivam/Desktop/code-clamp/src/content/docs/components/dropdown-search-bar.mdx"}, data: docs_5 }, { info: {"path":"components/filter-search-bar.mdx","absolutePath":"/home/shivam/Desktop/code-clamp/src/content/docs/components/filter-search-bar.mdx"}, data: docs_6 }, { info: {"path":"components/interactive-terminal.mdx","absolutePath":"/home/shivam/Desktop/code-clamp/src/content/docs/components/interactive-terminal.mdx"}, data: docs_7 }, { info: {"path":"components/matrix-terminal.mdx","absolutePath":"/home/shivam/Desktop/code-clamp/src/content/docs/components/matrix-terminal.mdx"}, data: docs_8 }, { info: {"path":"components/retro-terminal.mdx","absolutePath":"/home/shivam/Desktop/code-clamp/src/content/docs/components/retro-terminal.mdx"}, data: docs_9 }, { info: {"path":"components/serach-bar-index.mdx","absolutePath":"/home/shivam/Desktop/code-clamp/src/content/docs/components/serach-bar-index.mdx"}, data: docs_10 }, { info: {"path":"components/terminal-index.mdx","absolutePath":"/home/shivam/Desktop/code-clamp/src/content/docs/components/terminal-index.mdx"}, data: docs_11 }]);
export const meta = _runtime.meta<typeof _source.meta>([{ info: {"path":"meta.json","absolutePath":"/home/shivam/Desktop/code-clamp/src/content/docs/meta.json"}, data: meta_0 }]);